# Generated by Django 3.0.8 on 2020-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cgpa',
            field=models.CharField(default=6.0, max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.CharField(choices=[('core', 'core'), ('non-core', 'non-core')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_of_place',
            field=models.CharField(choices=[('On-campus', 'on-campus'), ('PPO', 'PPO'), ('off-campus', 'off-campus')], default='1', max_length=20),
        ),
    ]
